/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

SemaphoreHandle_t sem_write_mpu_done;
SemaphoreHandle_t sem_read_mpu_done;

extern float angle_pitch;
extern float angle_roll;
extern PID_State roll_pid;
extern PID_State pitch_pid;

#define TARGET_ANGLE_ROLL   0.0f
#define TARGET_ANGLE_PITCH  0.0f

#define SERVO_ROLL_HOME   90.0f
#define SERVO_PITCH_HOME  105.0f

void Task_I2C_MPU(void *pvParameters)
{
    vTaskDelay(100);                                                //block task trong 100ms cho mpu ổn định
	Init_MPU();
	xSemaphoreTake(sem_write_mpu_done, portMAX_DELAY);              //chờ khóa báo hoàn thành quá trình đọc
	Init_MPU();
	xSemaphoreTake(sem_write_mpu_done, portMAX_DELAY);              //chờ khóa báo hoàn thành quá trình ghi
    TickType_t xLastWakeTime = xTaskGetTickCount();                 //tạo 1 biến đếm
    while(1)
    {
        vTaskDelayUntil(&xLastWakeTime, 10);                        //chạy trong thì block, đủ 10ms thoát block
        RUN_MPU();                      
        xSemaphoreTake(sem_read_mpu_done, portMAX_DELAY);           //chờ khóa báo hoàn thành quá trình đọc
        Angle_Caculate();
    }
}

void Task_Control_Servo(void *pvParameters)
{
    TickType_t xLastWakeTime = xTaskGetTickCount();
    while(1)
    {
        vTaskDelayUntil(&xLastWakeTime, 20);
        /*float output_roll = PID_Compute(&roll_pid, angle_roll, TARGET_ANGLE_ROLL);
        TIMER2->CCR1 = AngleToCCR(SERVO_ROLL_HOME - output_roll);                           //ghi giá trị ccr vào thành ghi CCR1 
        float output_pitch = PID_Compute(&pitch_pid, angle_pitch, TARGET_ANGLE_PITCH);
        TIMER2->CCR2 = AngleToCCR(SERVO_PITCH_HOME - output_pitch);*/
    }
}

//=========================================gọi các hàm config===================================================//
void setup()
{
	DMA_I2C1_TXRX_Init();
    Servo_Config();
}

//=========================================cấu hình cho debug===================================================//

void setupMprint()
{
	SetClockGPIO(GPIOA);
	SetClockUART(UART1);
	GPIO_Init(GPIOA, GPIO_PIN_9, ALT_PUSHPULL, SPEED_10M);
	UART_Transmit_Init(UART1, DATA_8, BAU_9600);

	//mPrint("hahahaha\r\n");
}

//=========================================main===================================================//
int main(void)
{
	setup();
    setupMprint();

    sem_write_mpu_done = xSemaphoreCreateBinary();                                  //tạo 2 khóa semaphore cho quá trình đọc, ghi
    sem_read_mpu_done = xSemaphoreCreateBinary();

    xTaskCreate(Task_I2C_MPU, "Task_I2C_MPU", 512, NULL, 2, NULL);                  //tạo 2 task 
    xTaskCreate(Task_Control_Servo, "Task_Control_Servo", 512, NULL, 1, NULL);

    vTaskStartScheduler();                                                          //bắt đầu quá trình lập lịch
    while(1) 
    {

    }
}
